"""Embedding-based detection backend (frozen encoder + tiny numpy head).

Knowledge-distillation pipeline:
- Encoder: pre-trained MobileNetV3-Small ONNX (~5 MB) — frozen, used for
  feature extraction only. Same input → identical 1024-d embedding.
- Head: pure-numpy logistic regression trained from prior labels in the
  prospects DB (which were originally generated by Gemini in earlier
  scans — i.e. we distill those into a fast deterministic model).

Training: ``backend/scripts/auto_train_detection.py``
Inference: this module, called via ``services.detection_model``.

Public surface mirrors detection_ml + detection_gemini:
    is_available() -> bool
    detect(image_bytes, *, lat, zoom=20) -> dict (DetectionResult shape)
"""

from __future__ import annotations

import asyncio
import io
import logging
import threading
import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import numpy as np
    import onnxruntime as ort

log = logging.getLogger(__name__)

ENCODER_PATH = Path(__file__).resolve().parents[1] / "models" / "encoder" / "mobilenet_v3_small.onnx"
HEAD_PATH = Path(__file__).resolve().parents[1] / "models" / "head.npz"
THRESHOLD = 0.5
INPUT_SIZE = 224  # MobileNetV3 default
EMBED_DIM_FALLBACK = 1024  # validated against shape on first load

_session: ort.InferenceSession | None = None
_session_lock = threading.Lock()
_head: dict[str, np.ndarray] | None = None
_head_lock = threading.Lock()


def is_available() -> bool:
    """True iff encoder ONNX + trained head + onnxruntime are all present."""
    if not ENCODER_PATH.exists() or not HEAD_PATH.exists():
        return False
    try:
        import numpy  # noqa: F401
        import onnxruntime  # noqa: F401
        return True
    except ImportError:
        return False


def _get_session() -> ort.InferenceSession:
    global _session
    if _session is not None:
        return _session
    with _session_lock:
        if _session is not None:
            return _session
        if not ENCODER_PATH.exists():
            raise RuntimeError(
                f"Encoder ONNX missing at {ENCODER_PATH}. "
                "Run: python3 backend/scripts/download_encoder.py"
            )
        try:
            import onnxruntime as ort
        except ImportError as e:
            raise RuntimeError("onnxruntime not installed") from e
        opts = ort.SessionOptions()
        opts.intra_op_num_threads = 1
        opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
        _session = ort.InferenceSession(
            str(ENCODER_PATH), sess_options=opts, providers=["CPUExecutionProvider"]
        )
        return _session


def _get_head() -> dict[str, np.ndarray]:
    global _head
    if _head is not None:
        return _head
    with _head_lock:
        if _head is not None:
            return _head
        if not HEAD_PATH.exists():
            raise RuntimeError(
                f"Trained head missing at {HEAD_PATH}. "
                "Run: make train-detection (after collecting labelled scans)."
            )
        import numpy as np
        with np.load(HEAD_PATH) as npz:
            payload = {"weights": npz["weights"], "bias": npz["bias"]}
            if "version" in npz:
                payload["version"] = npz["version"]
        _head = payload
        return _head


def reset_session_for_tests() -> None:
    global _session, _head
    with _session_lock:
        _session = None
    with _head_lock:
        _head = None


# ─── Image preprocessing (ImageNet-style) ──────────────────────────────────

# Standard ImageNet mean/std applied to MobileNetV3.
_MEAN = (0.485, 0.456, 0.406)
_STD = (0.229, 0.224, 0.225)


def _preprocess(image_bytes: bytes) -> np.ndarray:
    """Decode → resize → normalize to ImageNet stats → NCHW float32."""
    if not image_bytes:
        raise RuntimeError("empty image bytes")
    try:
        import numpy as np
        from PIL import Image
    except ImportError as e:
        raise RuntimeError("Pillow + numpy required") from e
    try:
        img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    except Exception as e:
        raise RuntimeError(f"could not decode image: {e}") from e
    img = img.resize((INPUT_SIZE, INPUT_SIZE), Image.BILINEAR)
    arr = np.asarray(img, dtype=np.float32) / 255.0
    mean = np.array(_MEAN, dtype=np.float32).reshape(1, 1, 3)
    std = np.array(_STD, dtype=np.float32).reshape(1, 1, 3)
    arr = (arr - mean) / std
    return arr.transpose(2, 0, 1)[None, ...].astype(np.float32)


# ─── Embedding + classification ────────────────────────────────────────────


def embed(image_bytes: bytes) -> np.ndarray:
    """Run the frozen encoder. Pure feature-extraction; no labelling.

    Exposed as a public API so the auto-train script can re-use it.
    Returns a 1-D float32 vector.
    """
    import numpy as np

    sess = _get_session()
    tensor = _preprocess(image_bytes)
    inputs = {sess.get_inputs()[0].name: tensor}
    outputs = sess.run(None, inputs)
    raw = outputs[0]
    flat = np.asarray(raw, dtype=np.float32).reshape(-1)
    # L2-normalize so the head sees unit-norm vectors regardless of encoder.
    norm = float(np.linalg.norm(flat))
    if norm > 0:
        flat = flat / norm
    return flat


def _predict(embedding: np.ndarray) -> float:
    """Apply the trained head to one embedding → probability in [0, 1]."""
    import numpy as np

    head = _get_head()
    weights = head["weights"]
    bias = float(head["bias"])
    if embedding.shape[-1] != weights.shape[-1]:
        raise RuntimeError(
            f"embedding dim {embedding.shape[-1]} does not match head dim "
            f"{weights.shape[-1]}; retrain head against current encoder"
        )
    logit = float(np.dot(embedding, weights)) + bias
    # Sigmoid, numerically stable
    if logit >= 0:
        return float(1.0 / (1.0 + np.exp(-logit)))
    e = float(np.exp(logit))
    return e / (1.0 + e)


def _detect_sync(image_bytes: bytes, *, lat: float, zoom: int) -> dict:
    t0 = time.perf_counter()
    vec = embed(image_bytes)
    confidence = max(0.0, min(1.0, _predict(vec)))
    has_panels = confidence >= THRESHOLD
    panel_area_m2: float | None = None
    if has_panels:
        # No segmentation mask available — derive a rough estimate from
        # confidence × known tile area at this lat/zoom. Honest heuristic.
        from services.detection_geom import meters_per_pixel

        mpp = meters_per_pixel(lat, zoom)
        # Assume tile is 512x512 (matches services.satellite default).
        tile_area = (512 * mpp) ** 2
        # Scale by confidence — saturated panels ≈ 30% of tile typically.
        panel_area_m2 = confidence * 0.30 * tile_area
        if panel_area_m2 <= 0:
            panel_area_m2 = None
            has_panels = False
    return {
        "has_panels": has_panels,
        "confidence": confidence,
        "panel_area_m2": panel_area_m2,
        "roof_area_m2": panel_area_m2,
        "inference_ms": int((time.perf_counter() - t0) * 1000),
        "backend": "embed",
    }


async def detect(image_bytes: bytes, *, lat: float, zoom: int = 20) -> dict:
    return await asyncio.to_thread(_detect_sync, image_bytes, lat=lat, zoom=zoom)
