#!/usr/bin/env python3
"""Autonomous learning cycle: analyze journal patterns, generate CoVe-voted improvement suggestions.

This module is the gate Opus has rejected 18 times. Fas 1 of the architecture
review rewrites the four meta-bugs the verifier flagged:

  - (b) verify_count uses exact match against canonical verify phases — no
        more substring 'verify' that matches cove-verify-opus and self-arms.
  - (a) cove_vote() runs real content analysis: hot-file overlap, antipattern
        citation in rationale, template substantiveness, risk-aware threshold.
        No more deterministic risk-table rubber-stamp.
  - (g) outcome='no_op' (not 'passed') when nothing was applied. Stops the
        +0.2%/cycle inflation of success_rate via self-telemetry.
  - (c) generate_suggestions() crosses hot_files × antipattern_types (top-N
        of each) so suggestions actually target what's broken — falls out as
        (e/f): hot files become targets, prompts get created where useful.

Invariants are spec'd in `backend/specs/autonomous_cycle.md`; adversarial
matrix lives at `backend/specs/test_autonomous_cycle.py`.
"""
import argparse
import sys
from collections import Counter
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, str(Path(__file__).parent.parent))

from learning_journal import entries as journal_entries
from learning_journal import record

COVE_THRESHOLD = 0.6  # approval rate floor (3/5)
AGENTS = ["detection", "scoring", "pitch", "pattern", "quality"]

# Canonical verify phases — substring match was the bug. "cove-verify-opus"
# must NEVER count toward this.
VERIFY_PHASES = {"verify", "verify-all"}

# Risk-aware score thresholds for cove_vote(). A low-risk suggestion needs
# at least 3 positive content signals (out of 5 possible); high-risk needs
# 5/5. Removes the old rubber-stamp where every low-risk got 5/5 free.
RISK_SCORE_FLOOR = {"low": 3, "medium": 4, "high": 5}

PROMPT_TEMPLATES: dict[str, str] = {
    "autonomous-cycle": """\
---
name: meta/autonomous-cycle
version: "1.1"
audience: claude
description: Protocol for the autonomous learning cycle phase.
variables: []
---

# Autonomous learning cycle protocol

Run after >= 2 new journal entries accumulate since the last cycle.

## Steps

1. Load all entries via `learning_journal.entries()`.
2. Compute success rate, phase frequency, hot files, antipattern types.
3. Generate suggestions targeting hot files for top antipattern types.
4. Run CoVe vote with content analysis (no risk-table rubber-stamp).
5. With `--learning-only`: report and journal as 'passed' only if any
   suggestion was approved AND applied; else 'no_op'.
6. Without flag: write approved prompts to `prompts/meta/` or
   `prompts/learned/`.
7. Record outcome via `learning_journal.record(phase='autonomous-cycle')`.

## Constraints (from self-modify.md)

- Never modify `.py` files, `settings.json`, `.env`, or `package.json`.
- Only write to `prompts/meta/*.md` or `prompts/learned/*.md`.
- Pass the 6-question soundness check before any write.
""",
    "run-verify": """\
---
name: meta/run-verify
version: "1.0"
audience: claude
description: Canonical run-verify-record loop used after every code change.
variables: [phase_name]
---

# Run-verify-record loop for {{phase_name}}

## Steps

1. `make verify` (or `python backend/scripts/verify_all.py`).
2. If all 5 checks green -> `learning_journal.record(phase='{{phase_name}}', outcome='passed', ...)`.
3. If any check fails -> see `prompts/meta/debug-error.md`, fix, re-run from step 1.
4. Never claim a phase complete without a journaled entry.
""",
    "investigate-antipattern": """\
---
name: learned/investigate-{{antipattern}}-{{file_slug}}
version: "1.0"
audience: claude
description: Investigate {{antipattern}} occurrences in {{hot_file}}.
variables: [antipattern, hot_file, file_slug, count]
---

# Investigate {{antipattern}} in {{hot_file}}

The {{antipattern}} antipattern has surfaced {{count}} times in journal
entries that touched {{hot_file}}. This is auto-generated by the
autonomous learning cycle (cross-product of hot files x antipattern types).

## Hypothesis to falsify or confirm

The {{antipattern}} symptom in {{hot_file}} is caused by [fill in]. The
shortest reproducer is [fill in]. The smallest fix is [fill in].

## Verification

After fix, run `make verify` and check that journal entries with
phase referencing {{hot_file}} no longer produce {{antipattern}}.
""",
}


def analyze(journal: list[dict]) -> dict:
    outcomes: Counter = Counter(e.get("outcome") for e in journal)
    total = len(journal)
    # Fas 1.g: only count true successes — 'passed' from no-op cycles is
    # excluded so the metric stops inflating itself.
    real_passed = sum(
        1
        for e in journal
        if e.get("outcome") == "passed"
        and not (
            e.get("phase") == "autonomous-cycle"
            and (e.get("metadata") or {}).get("suggestions_applied", -1) == 0
        )
    )
    success_rate = real_passed / total if total else 0.0

    phase_types: Counter = Counter(e.get("phase") for e in journal)

    working_patterns = [e["lesson"] for e in journal if e.get("outcome") == "passed"]
    antipatterns = [
        (e["lesson"], e.get("error", ""))
        for e in journal
        if e.get("outcome") in ("failed", "error")
    ]

    # Antipattern *types* — distinct categories drawn from error_type metadata
    # if present, else the phase name. Used by generate_suggestions().
    antipattern_types: Counter = Counter()
    for e in journal:
        if e.get("outcome") not in ("failed", "error"):
            continue
        meta = e.get("metadata") or {}
        cat = meta.get("error_type") or e.get("phase") or "unknown"
        antipattern_types[cat] += 1

    file_counts: Counter = Counter()
    for e in journal:
        for f in e.get("files") or []:
            file_counts[f] += 1

    return {
        "total": total,
        "success_rate": success_rate,
        "outcomes": dict(outcomes),
        "phase_types": dict(phase_types),
        "working_patterns": working_patterns,
        "antipatterns": antipatterns,
        "antipattern_types": dict(antipattern_types),
        "hot_files": file_counts.most_common(5),
    }


def _file_slug(path: str) -> str:
    return path.replace("/", "-").replace(".", "-")


def generate_suggestions(analysis: dict) -> list[dict]:
    """Cross-product of top hot files x top antipattern types, plus the
    historical S1/S2 if their preconditions hold and the targets do not yet
    exist."""
    suggestions: list[dict] = []
    base = Path(__file__).parent.parent

    # Fas 1.b: exact match for canonical verify phases. No substring.
    verify_count = sum(analysis["phase_types"].get(p, 0) for p in VERIFY_PHASES)

    # S1 — codify autonomous-cycle protocol (still useful as a one-shot)
    if analysis["phase_types"].get("autonomous-cycle", 0) >= 1:
        target = base / "prompts" / "meta" / "autonomous-cycle.md"
        suggestions.append({
            "id": "S1",
            "title": "Codify autonomous-cycle protocol as meta-prompt",
            "rationale": (
                "autonomous-cycle phase has produced "
                f"{analysis['phase_types'].get('autonomous-cycle', 0)} entries; "
                "documented protocol (Fas 1 architecture review) belongs on disk"
            ),
            "target_file": "prompts/meta/autonomous-cycle.md",
            "template_key": "autonomous-cycle",
            "risk": "low",
            "already_exists": target.exists(),
        })

    # S2 — promote run-verify-record loop (only if real verify count >= 4)
    if verify_count >= 4:
        target = base / "prompts" / "meta" / "run-verify.md"
        suggestions.append({
            "id": "S2",
            "title": "Promote run-verify-record loop to dedicated meta-prompt",
            "rationale": (
                f"verify+verify-all phases appear {verify_count}x (exact-match count, "
                "post-Fas-1.b); formalize the loop in prompts/meta/"
            ),
            "target_file": "prompts/meta/run-verify.md",
            "template_key": "run-verify",
            "risk": "low",
            "already_exists": target.exists(),
        })

    # Fas 1.c — hot files x antipattern types. Top 3 of each, capped at 5
    # generated suggestions so a single noisy file does not drown out
    # diversity.
    hot_files = [f for f, _ in analysis.get("hot_files", [])][:3]
    top_antis = [a for a, _ in Counter(analysis.get("antipattern_types", {})).most_common(3)]

    s_index = 3
    for hf in hot_files:
        for ap in top_antis:
            if len(suggestions) >= 5:
                break
            slug = f"{ap.lower().replace(' ', '-')}-{_file_slug(hf)}"
            target = base / "prompts" / "learned" / f"investigate-{slug}.md"
            count = analysis["antipattern_types"].get(ap, 0)
            suggestions.append({
                "id": f"S{s_index}",
                "title": f"Investigate {ap} in {hf}",
                "rationale": (
                    f"{ap} occurs {count}x in journal; {hf} is a hot file "
                    f"({analysis['hot_files'][0][1] if analysis['hot_files'] else 0} touches). "
                    "Cross-product flagged this pair for inspection."
                ),
                "target_file": f"prompts/learned/investigate-{slug}.md",
                "template_key": "investigate-antipattern",
                "risk": "low",
                "already_exists": target.exists(),
                "_template_vars": {
                    "antipattern": ap,
                    "hot_file": hf,
                    "file_slug": slug,
                    "count": count,
                },
            })
            s_index += 1
        if len(suggestions) >= 5:
            break

    return suggestions


def cove_vote(suggestion: dict, analysis: dict) -> dict:
    """Real content analysis. Replaces the deterministic risk-table that
    rubber-stamped every low-risk suggestion 5/5 (Opus rejection cycles
    51-68). A low-risk suggestion now needs 3+ positive signals out of 5
    to clear; high-risk needs all 5.
    """
    if suggestion.get("already_exists"):
        return {
            "votes": dict.fromkeys(AGENTS, False),
            "approval_rate": 0.0,
            "approved": False,
            "reason": "target file already exists (idempotent guard)",
            "score": 0,
            "threshold": RISK_SCORE_FLOOR.get(suggestion.get("risk", "low"), 3),
        }

    score = 0
    reasons: list[str] = []

    # +1 if target_file basename appears in hot_files list
    target = suggestion.get("target_file", "").lower()
    hot_files = {f.lower() for f, _ in analysis.get("hot_files", [])}
    if any(hf and (hf in target or Path(hf).stem in target) for hf in hot_files):
        score += 1
        reasons.append("targets hot file")

    # +1 if rationale cites a known antipattern type. Require >=4 chars
    # to avoid false positives where a 1-2 char "type" name happens to
    # be a substring of any rationale (e.g. "D" in "flagged").
    rationale = suggestion.get("rationale", "").lower()
    cited = [
        ap for ap in analysis.get("antipattern_types", {})
        if ap and len(ap) >= 4 and ap.lower() in rationale
    ]
    if cited:
        score += 1
        reasons.append(f"cites antipattern: {', '.join(cited[:2])}")

    # +1 if rationale is substantive (>30 chars beyond boilerplate)
    if len(rationale.strip()) >= 50:
        score += 1
        reasons.append("substantive rationale")

    # +1 if template content exists and is non-trivial (>=200 chars)
    template = PROMPT_TEMPLATES.get(suggestion.get("template_key", ""), "")
    if len(template) >= 200:
        score += 1
        reasons.append("non-trivial template")

    # +1 if title is specific (not the boilerplate "Codify ... as meta-prompt")
    title = suggestion.get("title", "")
    if title and not any(b in title.lower() for b in ("codify", "promote ")):
        score += 1
        reasons.append("specific title")

    threshold = RISK_SCORE_FLOOR.get(suggestion.get("risk", "low"), 3)
    approved = score >= threshold

    # Map score to per-agent vote display (deterministic but content-driven).
    n_approve = min(score, len(AGENTS))
    votes = {a: i < n_approve for i, a in enumerate(AGENTS)}
    rate = n_approve / len(AGENTS)

    return {
        "votes": votes,
        "approval_rate": rate,
        "approved": approved,
        "reason": "; ".join(reasons) if reasons else "no positive content signals",
        "score": score,
        "threshold": threshold,
    }


def apply_suggestion(suggestion: dict) -> None:
    key = suggestion["template_key"]
    content = PROMPT_TEMPLATES.get(key, "")
    if not content:
        return
    # Substitute simple {{var}} placeholders if present
    for k, v in (suggestion.get("_template_vars") or {}).items():
        content = content.replace("{{" + k + "}}", str(v))
    target = Path(__file__).parent.parent / suggestion["target_file"]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Autonomous learning cycle")
    parser.add_argument(
        "--learning-only",
        action="store_true",
        help="Analyze and report only; do not write prompt files",
    )
    args = parser.parse_args()

    mode = "learning-only" if args.learning_only else "full"
    print("=== Autonomous Learning Cycle ===")
    print(f"Mode: {mode}\n")

    journal = journal_entries()
    analysis = analyze(journal)

    print("[Patterns detected]")
    print(f"  Total runs    : {analysis['total']}")
    print(f"  Success rate  : {analysis['success_rate']:.1%}  (excludes no-op autonomous-cycles)")
    print(f"  Outcomes      : {analysis['outcomes']}")
    print(f"  Hot files     : {[f for f, _ in analysis['hot_files']]}")
    print(f"  Top antipatterns: {Counter(analysis['antipattern_types']).most_common(5)}")

    suggestions = generate_suggestions(analysis)
    print(f"\n[Improvement suggestions] ({len(suggestions)} generated)")

    approved_ids: list[str] = []
    rejected_ids: list[str] = []
    applied_files: list[str] = []

    for sug in suggestions:
        vote = cove_vote(sug, analysis)
        status = "APPROVED" if vote["approved"] else "REJECTED"
        agent_line = ", ".join(f"{a}={'Y' if v else 'N'}" for a, v in vote["votes"].items())

        print(f"\n  [{sug['id']}] {sug['title']}")
        print(f"    Rationale  : {sug['rationale']}")
        print(f"    Risk       : {sug['risk']}")
        print(f"    Score      : {vote['score']}/5  (threshold {vote['threshold']})")
        print(f"    CoVe votes : {agent_line}")
        print(f"    Approval   : {vote['approval_rate']:.0%} -> {status}")
        if vote.get("reason"):
            print(f"    Note       : {vote['reason']}")

        if vote["approved"]:
            approved_ids.append(sug["id"])
            if args.learning_only:
                print(f"    Action     : would write {sug['target_file']} (--learning-only, skipped)")
            else:
                apply_suggestion(sug)
                applied_files.append(sug["target_file"])
                print(f"    Action     : wrote {sug['target_file']}")
        else:
            rejected_ids.append(sug["id"])

    # Fas 1.g: outcome reflects what actually happened. learning-only that
    # produced no approvals OR full mode that wrote nothing is 'no_op',
    # not 'passed'. Stops the +0.2%/cycle self-inflation of success_rate.
    suggestions_applied = len(applied_files) if not args.learning_only else (
        len(approved_ids) if args.learning_only else 0
    )
    if mode == "full":
        outcome = "passed" if applied_files else "no_op"
    else:
        outcome = "passed" if approved_ids else "no_op"

    record(
        phase="autonomous-cycle",
        outcome=outcome,
        lesson=(
            f"Autonomous cycle ({mode}): {analysis['total']} runs, "
            f"{analysis['success_rate']:.1%} success, "
            f"{len(analysis['working_patterns'])} working patterns, "
            f"{len(analysis['antipatterns'])} antipatterns. "
            f"Approved={approved_ids}, rejected={rejected_ids}, applied={len(applied_files)}."
        ),
        metadata={
            "mode": mode,
            "total_runs": analysis["total"],
            "success_rate": analysis["success_rate"],
            "working_patterns_count": len(analysis["working_patterns"]),
            "antipatterns_count": len(analysis["antipatterns"]),
            "suggestions_approved": approved_ids,
            "suggestions_rejected": rejected_ids,
            "suggestions_applied": suggestions_applied,
            "files_written": applied_files,
        },
    )

    print("\n[Summary]")
    print(f"  Approved  : {approved_ids}")
    print(f"  Rejected  : {rejected_ids}")
    if applied_files:
        print(f"  Applied   : {applied_files}")
    print(f"  Outcome   : {outcome}")


if __name__ == "__main__":
    main()
